name: Automation

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  labeling:
    name: Label merge conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@1b1b1fcde06a9b3d089f3464c96417961dde1168 # v3.0.2
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
